// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeTracking.Models;

namespace TimeTracking.Migrations
{
    [DbContext(typeof(TimeTrackingContext))]
    partial class TimeTrackingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("TimeTracking.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<char>("EmployeeTypeCode");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("EmployeeTypeCode");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeTypeCode = 'D',
                            FirstName = "Ann",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 2,
                            EmployeeTypeCode = 'D',
                            FirstName = "Ben",
                            LastName = "Doe"
                        });
                });

            modelBuilder.Entity("TimeTracking.Models.EmployeeType", b =>
                {
                    b.Property<char>("Code")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Code");

                    b.ToTable("EmployeeTypes");

                    b.HasData(
                        new
                        {
                            Code = 'D',
                            Description = "Dayshift"
                        },
                        new
                        {
                            Code = 'N',
                            Description = "Nightshift"
                        });
                });

            modelBuilder.Entity("TimeTracking.Models.TimeEntry", b =>
                {
                    b.Property<int>("EmployeeId");

                    b.Property<DateTime>("DateWorked");

                    b.Property<int>("HoursWorked");

                    b.HasKey("EmployeeId", "DateWorked");

                    b.ToTable("TimeEntries");
                });

            modelBuilder.Entity("TimeTracking.Models.Employee", b =>
                {
                    b.HasOne("TimeTracking.Models.EmployeeType", "EmployeeType")
                        .WithMany()
                        .HasForeignKey("EmployeeTypeCode")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TimeTracking.Models.TimeEntry", b =>
                {
                    b.HasOne("TimeTracking.Models.Employee", "Employee")
                        .WithMany("TimeEntries")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
